// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6G7wA478gT6rgWg_cvYxavAHx9_-r2dI',
    appId: '1:479632547732:android:e9e5669bf1047218857981',
    messagingSenderId: '479632547732',
    projectId: 'soulpot-5fbe6',
    storageBucket: 'soulpot-5fbe6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC71ELaygCOjuwbAfI6M7xoG9EjD7RTc14',
    appId: '1:479632547732:ios:580453ecf3b0e842857981',
    messagingSenderId: '479632547732',
    projectId: 'soulpot-5fbe6',
    storageBucket: 'soulpot-5fbe6.appspot.com',
    androidClientId: '479632547732-m1frt6u0vona91h0aq7n50rjqc8ficnu.apps.googleusercontent.com',
    iosClientId: '479632547732-h2es5tbcl0lh3amnkn367j57m5l15let.apps.googleusercontent.com',
    iosBundleId: 'com.sokaii.soulpot',
  );
}
